name: Build and Push BorgBackup Container Image

on:
  workflow_call:
    inputs:
      borg_version:
        description: "BorgBackup major.minor version to build (e.g. 1.1 or 2.0)"
        type: string
        required: true
      prerelease:
        description: "Allow building of prerelease"
        type: boolean
        default: false
      base_image:
        description: "The base image to build and publish on."
        type: string
        default: "docker.io/python:3-slim-bullseye"
      distroless_image:
        description: "The distroless image to distribute on."
        type: string
        default: "gcr.io/distroless/base-debian11"
      tag_major_minor:
        description: "Assign {major} and {major}.{minor} tags to the image. (e.g. :1 or :1.2)"
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      borg_version:
        description: "BorgBackup major.minor version to build (e.g. 1.1 or 2.0)"
        type: string
        required: true
      prerelease:
        description: "Allow building of prerelease"
        type: boolean
        default: false
      base_image:
        description: "The base image to build and publish on."
        type: string
        default: "docker.io/python:3-slim-bullseye"
      distroless_image:
        description: "The distroless image to distribute on."
        type: string
        default: "gcr.io/distroless/base-debian11"
      tag_major_minor:
        description: "Assign {major} and {major}.{minor} tags to the image. (e.g. :1 or :1.2)"
        type: boolean
        default: true

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/borgbackup

# Build in sequence to reuse build cache for different borg versions
# Wait on workflow level as there can only be 1 pending job, ref https://github.com/community/community/discussions/5435
#concurrency: build-push
# Cache mounts `--mount=type=cache` are not persisted in gha cache https://github.com/moby/buildkit/issues/1512
# --> no reuse of build artifacts (e.g. pip) between version anyway, just build everything in parallel with a version specific cache.

jobs:
  prepare:
    name: Get BorgBackup target version
    runs-on: ubuntu-latest
    outputs:
      BORG_VERSION: ${{ steps.version.outputs.BORG_VERSION }}
    steps:
      - id: version
        name: Get BorgBackup target release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BORG_VERSION=$(gh api repos/borgbackup/borg/releases --jq 'map(select(.draft==false and .prerelease==${{ inputs.prerelease }} and (.tag_name | startswith("${{ inputs.borg_version }}"))))|max_by(.published_at).tag_name') &&
          [ -n "${BORG_VERSION}" ] && echo "BORG_VERSION=${BORG_VERSION}" >> $GITHUB_OUTPUT
  build-push:
    name: Build and Push BorgBackup Container Image
    needs: prepare
    env:
      BORG_VERSION: ${{ needs.prepare.outputs.BORG_VERSION }}
    outputs:
      # Workaround as collecting job output is tedious
      IMAGES: |
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-amd64 \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-arm64 \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-armv7 \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-ppc64le \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-s390x \
      DISTROLESS_IMAGES: |
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-amd64-distroless \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-arm64-distroless \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-armv7-distroless \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-ppc64le-distroless \
        ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-s390x-distroless \
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            suffix: -amd64
          - platform: linux/arm64
            suffix: -arm64
          - platform: linux/arm/v7
            suffix: -armv7
          - platform: linux/ppc64le
            suffix: -ppc64le
          - platform: linux/s390x
            suffix: -s390x
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: "${{ env.IMAGE }}:${{ env.BORG_VERSION }}${{ matrix.suffix }}"
          cache-from: type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}
          cache-to: type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }},mode=max
          platforms: ${{ matrix.platform }}
          build-args: |
            version=${{ env.BORG_VERSION }}
            base_image=${{ inputs.base_image }}
      - name: Build and self-test (distroless)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.distroless
          target: test
          pull: true
          outputs: type=cacheonly
          cache-from: |
            type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless-selftest
          cache-to: |
            type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless-selftest,mode=max
          platforms: ${{ matrix.platform }}
          build-args: |
            version=${{ env.BORG_VERSION }}
            borg_image=${{ env.IMAGE }}:${{ env.BORG_VERSION }}${{ matrix.suffix }}
            distroless_image=${{ inputs.distroless_image }}
      - name: Build and push (distroless)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.distroless
          pull: true
          push: true
          tags: "${{ env.IMAGE }}:${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless"
          cache-from: |
            type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless-selftest
            type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless
          cache-to: |
            type=gha,scope=borgbackup-${{ env.BORG_VERSION }}${{ matrix.suffix }}-distroless,mode=max
          platforms: ${{ matrix.platform }}
          build-args: |
            version=${{ env.BORG_VERSION }}
            borg_image=${{ env.IMAGE }}:${{ env.BORG_VERSION }}${{ matrix.suffix }}
            distroless_image=${{ inputs.distroless_image }}
  manifest:
    name: Create multiarch manifest
    needs:
      - prepare
      - build-push
    env:
      BORG_VERSION: ${{ needs.prepare.outputs.BORG_VERSION }}
      PLATFORM_IMAGES: ${{ needs.build-push.outputs.IMAGES }}
      PLATFORM_DISTROLESS_IMAGES: ${{ needs.build-push.outputs.DISTROLESS_IMAGES }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push manifest
        run: |
          TAGS=" --tag ${{ env.IMAGE }}:${{ env.BORG_VERSION }}"; \
          TAGS=" --tag ${{ secrets.DOCKERHUB_USERNAME }}/borgbackup:${{ env.BORG_VERSION }}"; \
          [ "${{ inputs.tag_major_minor }}" = "true" ] && TAGS+=" --tag ${{ env.IMAGE }}:${{ inputs.borg_version }}"; \
          [ "${{ inputs.tag_major_minor }}" = "true" ] && TAGS+=" --tag ${{ secrets.DOCKERHUB_USERNAME }}/borgbackup:${{ inputs.borg_version }}"; \
          docker buildx imagetools create ${TAGS} ${{ env.PLATFORM_IMAGES }}
      - name: Push manifest (distroless)
        run: |
          TAGS="  --tag ${{ env.IMAGE }}:${{ env.BORG_VERSION }}-distroless"; \
          TAGS+=" --tag ${{ secrets.DOCKERHUB_USERNAME }}/borgbackup:${{ env.BORG_VERSION }}-distroless"; \
          [ "${{ inputs.tag_major_minor }}" = "true" ] && TAGS+=" --tag ${{ env.IMAGE }}:${{ inputs.borg_version }}-distroless"; \
          [ "${{ inputs.tag_major_minor }}" = "true" ] && TAGS+=" --tag ${{ secrets.DOCKERHUB_USERNAME }}/borgbackup:${{ inputs.borg_version }}-distroless"; \
          docker buildx imagetools create ${TAGS} ${{ env.PLATFORM_DISTROLESS_IMAGES }}
