name: Update Container Image
on:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  updateContainer:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get latest BorgBackup release
        id: borgbackup
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/borgbackup/borg/releases/latest | jq -r ".tag_name")
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
#          push: true
          tags: |
            borgbackup:latest
            borgbackup:${{ steps.borgbackup.outputs.release_tag }}
          build-args: |
            version=${{ steps.borgbackup.outputs.release_tag }}