name: Build and push all supported versions of the BorgBackup container image

on:
  workflow_dispatch:
  #“Every day at 04:05.”
  schedule:
    - cron: "5 4 * * *"

jobs:
  call-build-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "1.1"
            prerelease: false
            tag_major_minor: true
            base_image: "docker.io/library/python:3.7-slim-bullseye"
            distroless_image: "gcr.io/distroless/base-debian11"
          - version: "1.2"
            prerelease: false
            tag_major_minor: true
            base_image: "docker.io/library/python:3.9-slim-bullseye"
            distroless_image: "gcr.io/distroless/base-debian11"
          - version: "2.0"
            prerelease: true
            tag_major_minor: true
            base_image: "docker.io/library/python:3.11-slim-bullseye"
            distroless_image: "gcr.io/distroless/cc-debian11"
    uses: ./.github/workflows/build-push.yaml
    secrets: inherit
    with:
      borg_version: ${{ matrix.version }}
      prerelease: ${{ matrix.prerelease }}
      tag_major_minor: ${{ matrix.tag_major_minor }}
      base_image: ${{ matrix.base_image }}
      distroless_image: ${{ matrix.distroless_image }}
